apiVersion: v1
kind: Service
metadata:
  name: hammerly-backend
  namespace: hammerly
  labels:
    app.kubernetes.io/name: hammerly-backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hammerly-backend
  ports:
    - name: http
      port: 5000
      targetPort: http

