CREATE TABLE hammerly.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    avatar_image TEXT NOT NULL DEFAULT '/images/user.jpg',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hammerly.auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    start_price NUMERIC(12, 2) NOT NULL,
    current_bid NUMERIC(12, 2) NOT NULL,
    image TEXT,
    condition TEXT,
    seller_id BIGINT NOT NULL REFERENCES hammerly.users(id),
    status TEXT NOT NULL DEFAULT 'active',
    start_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hammerly.bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL REFERENCES hammerly.auctions(id),
    bidder_id BIGINT NOT NULL REFERENCES hammerly.users(id),
    amount NUMERIC(12, 2) NOT NULL,
    bid_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hammerly.watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES hammerly.users(id),
    auction_id BIGINT NOT NULL REFERENCES hammerly.auctions(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT watchlist_user_auction_unique UNIQUE (user_id, auction_id)
);

CREATE TABLE hammerly.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES hammerly.users(id),
    card_type TEXT NOT NULL,
    card_number TEXT NOT NULL DEFAULT '',
    last_four TEXT NOT NULL,
    expiry_month INTEGER NOT NULL,
    expiry_year INTEGER NOT NULL,
    cardholder_name TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    billing_address TEXT NOT NULL DEFAULT '',
    billing_city TEXT NOT NULL DEFAULT '',
    billing_province TEXT NOT NULL DEFAULT '',
    billing_postal_code TEXT NOT NULL DEFAULT '',
    billing_country TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
