apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - data
  - backend
  - ai
  - worker
  - observability

labels:
  - pairs:
      app.kubernetes.io/part-of: hammerly
    includeSelectors: false
